import { useEffect, useMemo, useRef, useState, useLayoutEffect } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import type { Match, MatchSide, Team, Venue } from '../types'
import { useI18n } from '../i18n'
import { useSettings } from '../settings/SettingsContext'
import { useAppData } from '../data/DataContext'
import { displayTz, fmtDate, fmtTime, tzAbbr } from '../utils/time'
import {
  flagSrc,
  fmtTemp,
  localizedNote,
  placeholderLabel,
  sortMatches,
  STAGE_LABEL_KEY,
} from '../utils/helpers'
import Flag from '../components/Flag'
import Icon from '../components/Icon'
import './venues.css'

type HostCountry = Venue['country']

const COUNTRIES: HostCountry[] = ['US', 'CA', 'MX']

const HOST_KEY: Record<HostCountry, string> = { US: 'hostUS', CA: 'hostCA', MX: 'hostMX' }

const COUNTRY_COLOR: Record<HostCountry, string> = {
  US: 'var(--accent-2)',
  CA: 'var(--accent)',
  MX: 'var(--accent-3)',
}

const ROOF_KEY: Record<Venue['roof'], string> = {
  open: 'roofOpen',
  canopy: 'roofCanopy',
  retractable: 'roofRetractable',
  fixed: 'roofFixed',
}

const NOW_ISO = new Date().toISOString()

function monthShort(locale: string, monthIdx: number): string {
  return new Intl.DateTimeFormat(locale, { month: 'short', timeZone: 'UTC' }).format(
    new Date(Date.UTC(2026, monthIdx, 15)),
  )
}

/* ================= SVG map =================
 * Real geography: Natural Earth 50m outlines projected with a Lambert conformal
 * conic (north-america standard), pre-generated by scripts/genmap.mjs. */

import naMap from '../data/na-map.json'

const MAP_W = naMap.w
const MAP_H = naMap.h

/** project lat/lon with the exact parameters the map paths were generated with */
function project(lat: number, lon: number): { x: number; y: number } {
  const { n, F, rho0, lon0, scale, tx, minY, pad } = naMap.proj
  const D = Math.PI / 180
  const rho = F / Math.tan(Math.PI / 4 + (lat * D) / 2) ** n
  const th = n * (lon - lon0) * D
  const px = rho * Math.sin(th)
  const py = rho0 - rho * Math.cos(th)
  return { x: px * scale + tx, y: MAP_H - pad - (py - minY) * scale }
}

const COUNTRY_CLASS: Record<HostCountry, string> = { US: 'vn-us', CA: 'vn-ca', MX: 'vn-mx' }

interface LabelTweak {
  dx?: number
  dy?: number
  anchor?: 'start' | 'end'
}

// hand-tuned label nudges to avoid overlaps / right-edge overflow (keyed by venue id)
const LABEL_TWEAK: Record<string, LabelTweak> = {
  '400248623': { dy: -8 }, // Boston: above-right, clears NY/NJ label
  '400257536': { dy: 4 }, // New Jersey: right of pin (room before map edge)
  '400248622': { anchor: 'end', dx: -11, dy: 9 }, // Philadelphia: left-below
  '400222084': { dy: 11 }, // Mexico City: nudged down, clears Guadalajara
  '400252150': { anchor: 'end', dx: -11 }, // Guadalajara: left over the ocean
  '400238450': { dy: -8 }, // Monterrey: above-right
}

// per-venue map-label overrides where the localized city name is too long for
// the map — all 23 UI languages, every form <= 13 chars
const LABEL_OVERRIDE: Record<string, Record<string, string>> = {
  '400257521': {
    en: 'SF Bay Area',
    fr: 'Baie de SF',
    es: 'Bahía de SF',
    pt: 'Baía de SF',
    'pt-BR': 'Baía de SF',
    de: 'SF Bay Area',
    nl: 'SF Bay Area',
    cs: 'Záliv SF',
    hr: 'Zaljev SF',
    sv: 'SF Bay Area',
    no: 'SF Bay Area',
    ar: 'خليج SF',
    fa: 'خلیج SF',
    tr: 'SF Körfezi',
    uz: 'SF koʻrfazi',
    ja: 'SFベイエリア',
    ko: 'SF 베이',
    zh: '旧金山湾区',
    'zh-TW': '舊金山灣區',
    it: 'Baia di SF',
    ru: 'Залив СФ',
    uk: 'Затока СФ',
    id: 'Teluk SF',
  },
}

/** map label: full city name when it fits, else first words within ~13 chars */
function shortCity(name: string, venueId: string, lang: string): string {
  const override = LABEL_OVERRIDE[venueId]?.[lang]
  if (override) return override
  if (name.length <= 13) return name
  const words = name.split(/\s+/)
  const two = words.slice(0, 2).join(' ')
  return two.length <= 13 ? two : words[0]
}

/** team picker with real flag images (native <option> can't render components) */
function TeamDropdown({
  teams,
  value,
  onChange,
  allLabel,
  label,
}: {
  teams: Team[]
  value: string | null
  onChange: (code: string | null) => void
  allLabel: string
  label: string
}) {
  const { pick } = useI18n()
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const close = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    const esc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('mousedown', close)
    document.addEventListener('keydown', esc)
    return () => {
      document.removeEventListener('mousedown', close)
      document.removeEventListener('keydown', esc)
    }
  }, [open])

  const selected = value ? teams.find((tm) => tm.code === value) : null

  const choose = (code: string | null) => {
    onChange(code)
    setOpen(false)
  }

  return (
    <div className={`vn-dd${open ? ' open' : ''}${value ? ' has-sel' : ''}`} ref={ref}>
      <button
        type="button"
        className="vn-dd-btn"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={label}
        onClick={() => setOpen((o) => !o)}
      >
        {selected ? (
          <>
            <Flag team={selected} size={18} />
            <span className="vn-dd-name">{pick(selected.name, selected.code)}</span>
          </>
        ) : (
          <span className="vn-dd-name">{allLabel}</span>
        )}
        <Icon name="chevron" size={14} />
      </button>
      {value && (
        <button
          type="button"
          className="vn-dd-clear"
          aria-label={allLabel}
          title={allLabel}
          onClick={() => choose(null)}
        >
          <Icon name="close" size={13} />
        </button>
      )}
      {open && (
        <div className="vn-dd-list" role="listbox" aria-label={label}>
          <button type="button" role="option" aria-selected={value === null} onClick={() => choose(null)}>
            <span className="vn-dd-spacer" />
            {allLabel}
          </button>
          {teams.map((tm) => (
            <button
              type="button"
              key={tm.code}
              role="option"
              aria-selected={value === tm.code}
              onClick={() => choose(tm.code)}
            >
              <Flag team={tm} size={18} />
              {pick(tm.name, tm.code)}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

function VenueMap({
  venues,
  counts,
  camps,
  selTeam,
  selVenueIds,
  selMatchCount,
  flashVenue,
  onSelTeam,
  onPin,
  onCountry,
}: {
  venues: Venue[]
  counts: Record<HostCountry, number>
  camps: Team[]
  selTeam: string | null
  selVenueIds: ReadonlySet<string>
  selMatchCount: number
  flashVenue: string | null
  onSelTeam: (code: string | null) => void
  onPin: (id: string) => void
  onCountry: (c: HostCountry) => void
}) {
  const { t, pick, lang, locale } = useI18n()
  const navigate = useNavigate()
  const [showCamps, setShowCamps] = useState(true)

  // crop horizontal whitespace: hug the pins/labels/camps extent (the coasts),
  // which also ignores off-frame slivers like the Alaska fragment
  const contentRef = useRef<SVGGElement>(null)
  const [crop, setCrop] = useState<[number, number, number, number] | null>(null)
  useLayoutEffect(() => {
    const b = contentRef.current?.getBBox()
    if (b && b.width > 0) {
      const pad = 14
      const x0 = Math.max(Math.floor(b.x - pad), 0)
      const x1 = Math.min(Math.ceil(b.x + b.width + pad), MAP_W)
      const y0 = Math.max(Math.floor(b.y - pad), 0)
      const y1 = Math.min(Math.ceil(b.y + b.height + pad), MAP_H)
      setCrop([x0, y0, x1 - x0, y1 - y0])
    }
  }, [])

  const teamOptions = useMemo(
    () => camps.slice().sort((a, b) => pick(a.name, a.code).localeCompare(pick(b.name, b.code), locale)),
    [camps, pick, locale],
  )

  // project the camps, then run a deterministic collision-relaxation pass so no
  // flag overlaps another flag or a stadium pin (same-city camps fan out around it)
  const campPins = useMemo(() => {
    const venuePts = venues.map((v) => project(v.lat, v.lon))
    // city-label bounding boxes are obstacles too (12px font ≈ 6.6px/char)
    const labelRects = venues.map((v) => {
      const { x, y } = project(v.lat, v.lon)
      const tw = LABEL_TWEAK[v.id] ?? {}
      const anchor = tw.anchor ?? 'start'
      const dx = tw.dx ?? 11
      const dy = tw.dy ?? 4
      const w = shortCity(pick(v.cityName, v.city), v.id, lang).length * 6.6
      const x0 = anchor === 'start' ? x + dx : x + dx - w
      return { x0, x1: x0 + w, y0: y + dy - 11, y1: y + dy + 4 }
    })
    const pts = camps
      .flatMap((tm) => {
        const bc = tm.baseCamp
        return bc && bc.lat != null && bc.lon != null ? [{ tm, ...project(bc.lat, bc.lon) }] : []
      })
      .sort((a, b) => a.tm.code.localeCompare(b.tm.code))
    const W = 19 // min horizontal separation (flag is 17 wide)
    const H = 15 // min vertical separation (flag is 13 tall)
    for (let iter = 0; iter < 80; iter++) {
      let moved = false
      for (const p of pts) {
        for (const v of venuePts) {
          const dx = p.x - v.x
          const dy = p.y - v.y
          if (Math.abs(dx) < 17 && Math.abs(dy) < 15) {
            p.y += dy >= 0 ? 4 : -4 // slide off the stadium pin vertically
            moved = true
          }
        }
        for (const r of labelRects) {
          if (p.x + 9.5 > r.x0 && p.x - 9.5 < r.x1 && p.y + 7.5 > r.y0 && p.y - 7.5 < r.y1) {
            p.y += p.y >= (r.y0 + r.y1) / 2 ? 4 : -4 // slide off the city label
            moved = true
          }
        }
      }
      for (let i = 0; i < pts.length; i++) {
        for (let j = i + 1; j < pts.length; j++) {
          const a = pts[i]
          const b = pts[j]
          const dx = b.x - a.x
          const dy = b.y - a.y
          if (Math.abs(dx) < W && Math.abs(dy) < H) {
            const px = (W - Math.abs(dx)) / 2
            const py = (H - Math.abs(dy)) / 2
            if (px <= py) {
              const sgn = dx >= 0 ? 1 : -1
              a.x -= sgn * px
              b.x += sgn * px
            } else {
              const sgn = dy !== 0 ? (dy > 0 ? 1 : -1) : i % 2 ? 1 : -1
              a.y -= sgn * py
              b.y += sgn * py
            }
            moved = true
          }
        }
      }
      if (!moved) break
    }
    for (const p of pts) {
      p.x = Math.min(Math.max(p.x, 10), MAP_W - 10)
      p.y = Math.min(Math.max(p.y, 8), MAP_H - 8)
    }
    return pts
  }, [camps, venues, pick, lang])

  return (
    <div className="card vn-map-card">
      <div className="vn-map-wrap">
        <svg
          className="vn-svg"
          viewBox={crop ? crop.join(' ') : `0 0 ${MAP_W} ${MAP_H}`}
          role="group"
          aria-label={t('venuesSub')}
        >
          <path className="vn-ctx" d={naMap.context} />
          {COUNTRIES.map((c) => (
            <path key={c} className={`vn-country ${COUNTRY_CLASS[c]}`} d={naMap.countries[c]} />
          ))}
          <path className="vn-lakes" d={naMap.lakes} />

          <g ref={contentRef}>
            {showCamps &&
              campPins.map(({ tm, x, y }) => (
                <g
                  key={tm.code}
                  className={`vn-camp${selTeam && tm.code !== selTeam ? ' vn-dim' : ''}${selTeam === tm.code ? ' vn-camp-sel' : ''}`}
                  transform={`translate(${x.toFixed(1)} ${y.toFixed(1)})`}
                  role="button"
                  tabIndex={0}
                  aria-label={`${t('baseCamp')}: ${pick(tm.name, tm.code)}`}
                  onClick={() => navigate(`/team/${tm.code}`)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      navigate(`/team/${tm.code}`)
                    }
                  }}
                >
                  <title>{`${pick(tm.name, tm.code)} · ${tm.baseCamp?.facility || tm.baseCamp?.city || ''}`}</title>
                  <rect x={-8.5} y={-6.5} width={17} height={13} rx={1.5} className="vn-camp-bg" />
                  {tm.iso2 && (
                    <image
                      href={flagSrc(tm.iso2)}
                      x={-7.5}
                      y={-5.5}
                      width={15}
                      height={11}
                      preserveAspectRatio="xMidYMid meet"
                    />
                  )}
                </g>
              ))}

            {venues.map((v) => {
              const { x, y } = project(v.lat, v.lon)
              const tw = LABEL_TWEAK[v.id] ?? {}
              const anchor = tw.anchor ?? 'start'
              const dx = tw.dx ?? 11
              const dy = tw.dy ?? 4
              const color = COUNTRY_COLOR[v.country]
              const dim = selTeam !== null && !selVenueIds.has(v.id)
              return (
                <g
                  key={v.id}
                  className={`vn-pin${dim ? ' vn-dim' : ''}${flashVenue === v.id ? ' vn-flash' : ''}`}
                  transform={`translate(${x.toFixed(1)} ${y.toFixed(1)})`}
                  role="button"
                  tabIndex={0}
                  aria-label={v.realName}
                  onClick={() => onPin(v.id)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault()
                      onPin(v.id)
                    }
                  }}
                >
                  <title>{v.realName}</title>
                  <circle className="vn-halo" r="12" fill={color} />
                  <circle className="vn-core" r="6.5" fill={color} stroke="#fff" strokeWidth="2" />
                  <text className="vn-lbl" x={dx} y={dy} textAnchor={anchor}>
                    {shortCity(pick(v.cityName, v.city), v.id, lang)}
                  </text>
                </g>
              )
            })}
          </g>
        </svg>
      </div>

      <div className="vn-legend">
        {COUNTRIES.map((c) => (
          <button key={c} type="button" className="vn-leg" onClick={() => onCountry(c)}>
            <span className="vn-dot" style={{ background: COUNTRY_COLOR[c] }} aria-hidden="true" />
            <strong>{t(HOST_KEY[c])}</strong>
            <span className="muted small tnum">{t('matchesShown', { n: counts[c] })}</span>
          </button>
        ))}
        <button
          type="button"
          className={`vn-leg vn-leg-camps${showCamps ? '' : ' off'}`}
          aria-pressed={showCamps}
          onClick={() => setShowCamps((v) => !v)}
        >
          <span className="vn-camp-glyph" aria-hidden="true" />
          <strong>{t('baseCamp')}</strong>
          <span className="muted small tnum">{campPins.length}</span>
        </button>
        <span className="vn-team-filter">
          <TeamDropdown
            teams={teamOptions}
            value={selTeam}
            onChange={onSelTeam}
            allLabel={t('allTeams')}
            label={t('filterTeams')}
          />
          {selTeam && (
            <span className="muted small vn-team-hint tnum">{t('matchesShown', { n: selMatchCount })}</span>
          )}
        </span>
      </div>
    </div>
  )
}

/* ================= match rows ================= */

function VenueMatchRow({ m, tz }: { m: Match; tz?: string }) {
  const { t, pick, locale } = useI18n()
  const { teams } = useAppData()
  const played = m.status === 'finished' || m.status === 'live'

  const side = (s: MatchSide | null, ph: string | null, right: boolean) => {
    const team = s ? teams[s.code] : null
    const label = s ? (team ? pick(team.name, s.code) : s.code) : ph ? placeholderLabel(ph, t) : t('tbd')
    return (
      <span className={`vn-mside${right ? ' right' : ''}`}>
        {!right && team && <Flag team={team} size={18} />}
        <span className={`vn-tname${team ? '' : ' tbd'}`}>{label}</span>
        {right && team && <Flag team={team} size={18} />}
      </span>
    )
  }

  return (
    <Link to={`/match/${m.id}`} className={`vn-mrow${m.status === 'live' ? ' live' : ''}`}>
      <span className="vn-mwhen small tnum">
        <b>{fmtDate(m.date, locale, tz)}</b>
        {m.status === 'live' ? (
          <span className="chip chip-live">{t('statusLive')}</span>
        ) : (
          <span className="muted">{fmtTime(m.date, locale, tz)}</span>
        )}
      </span>
      <span className="vn-mteams">
        {side(m.home, m.phA, false)}
        <span className={played && m.home && m.away ? 'vn-msc tnum' : 'vn-mvs muted small'}>
          {played && m.home && m.away ? `${m.home.score ?? '–'}–${m.away.score ?? '–'}` : t('vs')}
        </span>
        {side(m.away, m.phB, true)}
      </span>
      <span className="chip vn-mstage">
        {m.stage === 'group' && m.group ? t('groupX', { x: m.group }) : t(STAGE_LABEL_KEY[m.stage])}
      </span>
    </Link>
  )
}

/* ================= venue card ================= */

function VenueCard({ venue: v, matches }: { venue: Venue; matches: Match[] }) {
  const { t, pick, locale } = useI18n()
  const { settings } = useSettings()
  const [open, setOpen] = useState(false)
  const tz = displayTz(settings, v)
  const fifa = pick(v.fifaName)
  const cl = v.climate

  return (
    <article id={`venue-${v.id}`} className="card vn-card">
      <div className="vn-body">
        <div className="vn-head">
          <div className="vn-names">
            <h3 className="vn-name">{v.realName}</h3>
            {fifa && fifa !== v.realName && <div className="vn-fifa muted small">{fifa}</div>}
          </div>
          <span className="vn-dot lg" style={{ background: COUNTRY_COLOR[v.country] }} aria-hidden="true" />
        </div>

        <div className="vn-city small muted">
          <Icon name="pin" size={14} />
          <span>{pick(v.cityName, v.city)}</span>
        </div>

        <div className="vn-chips">
          <span className="chip tnum">
            <Icon name="stadium" size={13} />
            {t('capacityK', { n: v.capacity.toLocaleString(locale) })}
          </span>
          <span className="chip">{t(ROOF_KEY[v.roof])}</span>
          <span className="chip">
            <Icon name="clock" size={13} />
            {tzAbbr(NOW_ISO, locale, v.tz)}
          </span>
        </div>

        {cl && (cl.jun || cl.jul) && (
          <div className="vn-climate small">
            <span className="vn-temps tnum">
              {cl.jun && (
                <>
                  {monthShort(locale, 5)}{' '}
                  <b>
                    {fmtTemp(cl.jun.highC, settings.units)}/{fmtTemp(cl.jun.lowC, settings.units)}
                  </b>
                </>
              )}
              {cl.jun && cl.jul && <span className="muted"> · </span>}
              {cl.jul && (
                <>
                  {monthShort(locale, 6)}{' '}
                  <b>
                    {fmtTemp(cl.jul.highC, settings.units)}/{fmtTemp(cl.jul.lowC, settings.units)}
                  </b>
                </>
              )}
            </span>
            {localizedNote(cl.rainNote, pick) && (
              <div className="vn-rain muted">{localizedNote(cl.rainNote, pick)}</div>
            )}
          </div>
        )}

        {v.wiki && (
          <div className="vn-wiki small">
            <a href={v.wiki.url} target="_blank" rel="noopener noreferrer" title={t('wikipedia')}>
              {v.wiki.title}
              <Icon name="external" size={13} />
            </a>
          </div>
        )}
      </div>

      <button type="button" className="vn-expand" aria-expanded={open} onClick={() => setOpen((o) => !o)}>
        <Icon name="calendar" size={15} />
        <span>{t('matchesAtVenue')}</span>
        <span className="chip tnum">{matches.length}</span>
        <Icon name="back" size={14} className={`vn-caret${open ? ' open' : ''}`} />
      </button>

      {open && (
        <div className="vn-mlist">
          {matches.map((m) => (
            <VenueMatchRow key={m.id} m={m} tz={tz} />
          ))}
        </div>
      )}
    </article>
  )
}

/* ================= page ================= */

export default function Venues() {
  const { t } = useI18n()
  const data = useAppData()

  const venueList = useMemo(() => Object.values(data.venues), [data.venues])
  const camps = useMemo(() => Object.values(data.teams), [data.teams])

  // deep links: #/venues?team=CODE pre-selects the map filter, ?venue=ID flashes a pin
  const [searchParams] = useSearchParams()
  const mapRef = useRef<HTMLDivElement>(null)

  // map filter: only the venues where the selected team plays
  const [selTeam, setSelTeam] = useState<string | null>(() => {
    const tm = searchParams.get('team')
    return tm && data.teams[tm] ? tm : null
  })
  const [flashVenue, setFlashVenue] = useState<string | null>(() => {
    const v = searchParams.get('venue')
    return v && data.venues[v] ? v : null
  })
  // biome-ignore lint/correctness/useExhaustiveDependencies: deep-link handling runs once on mount by design
  useEffect(() => {
    if (!flashVenue && !searchParams.get('team')) return
    mapRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    if (!flashVenue) return
    const id = window.setTimeout(() => setFlashVenue(null), 3200)
    return () => window.clearTimeout(id)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  const { selVenueIds, selMatchCount } = useMemo(() => {
    const ids = new Set<string>()
    let count = 0
    if (selTeam) {
      for (const m of data.matches) {
        if (m.home?.code === selTeam || m.away?.code === selTeam) {
          count++
          if (m.venueId) ids.add(m.venueId)
        }
      }
    }
    return { selVenueIds: ids, selMatchCount: count }
  }, [data.matches, selTeam])

  const matchesByVenue = useMemo(() => {
    const byId = new Map(data.matches.map((m): [string, Match] => [m.id, m]))
    const out = new Map<string, Match[]>()
    for (const v of venueList) {
      out.set(v.id, sortMatches(v.matches.map((id) => byId.get(id)).filter((m): m is Match => !!m)))
    }
    return out
  }, [data.matches, venueList])

  const counts = useMemo(() => {
    const c: Record<HostCountry, number> = { US: 0, CA: 0, MX: 0 }
    for (const v of venueList) c[v.country] += (matchesByVenue.get(v.id) ?? []).length
    return c
  }, [venueList, matchesByVenue])

  const sections = useMemo(
    () =>
      COUNTRIES.map((c) => ({
        country: c,
        venues: venueList
          .filter((v) => v.country === c)
          // fixed order in every language: tournament weight first
          // (matches hosted desc, then capacity desc, then stable id)
          .sort(
            (a, b) =>
              b.matches.length - a.matches.length || b.capacity - a.capacity || a.id.localeCompare(b.id),
          ),
      })),
    [venueList],
  )

  const scrollToVenue = (id: string) => {
    const el = document.getElementById(`venue-${id}`)
    if (!el) return
    el.scrollIntoView({ behavior: 'smooth', block: 'center' })
    el.classList.remove('vn-hl')
    void el.offsetWidth // restart the highlight animation
    el.classList.add('vn-hl')
    window.setTimeout(() => el.classList.remove('vn-hl'), 2000)
  }

  const scrollToCountry = (c: HostCountry) => {
    document.getElementById(`vn-country-${c}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  return (
    <div className="vn-page">
      <div className="page-head">
        <h1>{t('venuesTitle')}</h1>
        <p>{t('venuesSub')}</p>
      </div>

      <div ref={mapRef} className="vn-map-anchor">
        <VenueMap
          venues={venueList}
          counts={counts}
          camps={camps}
          selTeam={selTeam}
          selVenueIds={selVenueIds}
          selMatchCount={selMatchCount}
          flashVenue={flashVenue}
          onSelTeam={setSelTeam}
          onPin={scrollToVenue}
          onCountry={scrollToCountry}
        />
      </div>

      {sections.map(({ country, venues }) => (
        <section key={country} id={`vn-country-${country}`} className="vn-country-sec">
          <div className="section-title">
            <Flag iso2={country} size={26} alt={t(HOST_KEY[country])} />
            <h2>{t(HOST_KEY[country])}</h2>
            <span className="muted small tnum">{t('matchesShown', { n: counts[country] })}</span>
          </div>
          <div className="cards-grid three">
            {venues.map((v) => (
              <VenueCard key={v.id} venue={v} matches={matchesByVenue.get(v.id) ?? []} />
            ))}
          </div>
        </section>
      ))}
    </div>
  )
}
